EasyERP/EasyERP/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EasyERP.Context;
using EasyERP.Models;
using EasyERP.Models.HelpModels;
using PagedList;

namespace EasyERP.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        [HttpGet]
        public ActionResult AllClients(int? page)
        {
            return View(GetClients(page));
        }

        [HttpGet]
        public ActionResult AddClient()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddClient(Client client)
        {
            if (ModelState.IsValid)
            {
                using (var db = new DBContext())
                {
                    using (var transaction = db.Database.BeginTransaction())
                    {
                        try
                        {
                            client.Notes.ToList()[0].EnteredOn = DateTime.Now;
                            client.Notes.ToList()[0].EnteredBy = "System";
                            client.CompanyCode = (db.Clients.Max(m => m.ClientId) + 1).ToString();
                            db.Clients.Add(client);
                            db.SaveChanges();

                            transaction.Commit();
                        }
                        catch (Exception ex)
                        {
                            transaction.Rollback();
                            ViewBag.Error = ex.Message;
                            return View();
                        }
                    }
                }
                return RedirectToAction("AllClients");
            }
            return View();
        }

        
        [HttpGet]
        public ActionResult DetailsClient(int id)
        {
            ClientOrders ClientOrders = new ClientOrders();
            try
            {
                ClientOrders.Client = GetClient(id);
                ClientOrders.Orders = OrdersController.GetOrders(id);
                ViewBag.Edit = false;
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
            }
            return View(ClientOrders);
        }

        [HttpGet]
        public ActionResult EditClient(int id)
        {
            Client client = null;
            try
            {
                client = GetClient(id);
                ViewBag.Edit = true;
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
            return View(client);
        }

        [HttpPost]
        public ActionResult EditClient(Client client, int? ClientId)
        {
            if (ModelState.IsValid)
            {
                client.ClientId = ClientId ?? 0;
                using (var db = new DBContext())
                {
                    using (var transaction = db.Database.BeginTransaction())
                    {
                        try
                        {
                            db.Entry(client).State = EntityState.Modified;
                            db.SaveChanges();

                            transaction.Commit();
                        }
                        catch (Exception ex)
                        {
                            transaction.Rollback();
                            ViewBag.Error = ex.Message;
                            return RedirectToAction("EditClient", new { id = client.ClientId });
                        }
                    }
                }
                return RedirectToAction("DetailsClient", new { id = client.ClientId });
            }
            return View();
        }

        private PagedList.IPagedList<Client> GetClients(int? page)
        {
            int pageNumber = page ?? 1;
            List<Client> Clients = new List<Client>();
            using (DBContext db = new DBContext())
            {
                Clients = db.Clients.ToList();
            }
            return Clients.ToPagedList(pageNumber, Global.Global.pageSize);
        }

        public static Client GetClient(int id)
        {
            Client client = null;
            using (DBContext db = new DBContext())
            {
                var clients = from c in db.Clients where c.ClientId == id select c;
                client = clients.First();
            }
            return client;
        }

        [HttpGet]
        public ActionResult EditClientAsync(int id)
        {
            Client model = GetClient(id);
            return PartialView("_ClientAddEdit", model);
        }
    }
}

EasyERP/EasyERP/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyERP.Context;
using EasyERP.Models;
using System.Data.Entity.Core.Objects;
using PagedList;

namespace EasyERP.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Products
        public ActionResult Index(int? page)
        {
            int pageNumber = page ?? 1;
            List<Product> products = db.Products.ToList();
            return View(products.ToPagedList(pageNumber, Global.Global.pageSize));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,Name,Code,Amount,ListPrice,PurchasePrice,QuantityPackage,Category,DeliveryDate,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                db.Entry(product).GetDatabaseValues();
                product.Code = product.ProductId.ToString();
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,Name,Code,Amount,ListPrice,PurchasePrice,QuantityPackage,Category,DeliveryDate,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EasyERP/EasyERP/Controllers/ReportsController.cs
using EasyERP.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EasyERP.Models;
using Newtonsoft.Json;

namespace EasyERP.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        DBContext db = new DBContext();

        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public string Report1()
        {
            TopSeller topSeller = new TopSeller();

            List<User> usersList = db.Users.ToList();

            foreach (User item in usersList)
            {
                //Add Label 
                string seller = item.FirstName + " " + item.LastName;
                topSeller.label.Add(seller);
                List<decimal> ordersPrice = db.Orders.Where(o => o.Seller == seller).Select(o => o.PurchasePrice).ToList();
                decimal Price = 0;
                foreach (decimal price in ordersPrice)
                {
                    Price += price;

                }
                topSeller.value.Add(Price);

            }
            return JsonConvert.SerializeObject(topSeller);
        }

        [HttpPost]
        [AllowAnonymous]
        public string Report2()
        {
            TopSeller topSeller = new TopSeller();
            topSeller.label.AddRange(new string[] { "Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień" });

            for (int i = 1; i <= 12; i++)
            {
                DateTime dateStart = new DateTime(2014, i, 1);
                DateTime dateEnd = new DateTime(2014, i, DateTime.DaysInMonth(2014, i));
                List<decimal> ordersPrice = db.Orders.Where(o => o.StartDate >= dateStart && o.StartDate <= dateEnd).Select(o => o.PurchasePrice).ToList();
                decimal price = 0;
                foreach (decimal item in ordersPrice)
                {
                    price += item;
                }
                topSeller.value.Add(price);
            }
            return JsonConvert.SerializeObject(topSeller);
        }

        [HttpPost]
        [AllowAnonymous]
        public string Report3()
        {
            bool flag = true;
            TopSeller topSeller = new TopSeller();
            var list = from c in db.Clients
                       from o in db.Orders
                       where (c.ClientId == o.Client.ClientId)
                       select new { c.FirstName, c.LastName, o.PurchasePrice };
            var result = list
                        .GroupBy(a => new { a.FirstName, a.LastName })
                        .Select(a => new { Amount = a.Sum(b => b.PurchasePrice), Name = a.Key })
                        .OrderByDescending(a => a.Amount)
                        .ToList();
            foreach (var item in result)
            {
                topSeller.label.Add(item.Name.FirstName + " " + item.Name.LastName);
                topSeller.value.Add(item.Amount);
            }
            return JsonConvert.SerializeObject(topSeller);
        }
    }

    public class TopSeller
    {
        public TopSeller()
        {
            label = new List<string>();
            value = new List<decimal>();
        }
        public List<string> label { get; set; }
        public List<decimal> value { get; set; }
    }


}

EasyERP/EasyERP/Controllers/SettingsController.cs
using EasyERP.Context;
using EasyERP.HelperClass;
using EasyERP.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EasyERP.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        DBContext db = new DBContext();
        // GET: Settings
        public ActionResult Basic()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SettingsUsers()
        {
            var users = db.Users.ToList();
            ViewBag.User = CreateUserDefault();
            return PartialView("_SettingsUsers", users);
        }

        [HttpGet]
        public ActionResult SettingsCompany()
        {
            var company = db.Companies.FirstOrDefault();
            if (company == null)
                company = new Company();
            return PartialView("_SettingsCompany", company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SettingsCompany(Company company)
        {
            if (ModelState.IsValid)
            {
                var companyOld = db.Companies.Find(company.CompanyId);
                if (companyOld == null)
                {
                    db.Companies.Add(company);
                    db.SaveChanges();
                }
                else
                {
                    using (db = new DBContext())
                    {
                        db.Entry(company).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }

            }
            ViewBag.Success = "Zapisano ustawienia firmy";
            return View("Basic");
        }

        [HttpPost]
        public ActionResult AddUser(User user)
        {
            try
            {
                var checkUser = db.Users.Where(u => u.Name == user.Name).FirstOrDefault();
                if (checkUser != null)
                    throw new Exception("Uzytkownik o podanym Loginie już istnieje.");
                var password = Encryption.GetSaltedHash(user.Password, user.Name);
                user.Password = password;
                user.EnteredOn = DateTime.Now;
                db.Users.Add(user);
                db.SaveChanges();
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                //ViewBag.User = user;
                //return PartialView("_SettingsUsers", db.Users.ToList());
            }
            return View("Basic");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var user = db.Users.Find(id);
            ViewBag.User = CreateUserDefault();
            user.Password = string.Empty;
            return PartialView("_EditUser", user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            ViewBag.User = CreateUserDefault();
            if (ModelState.IsValid)
            {
                var password = Encryption.GetSaltedHash(user.Password, user.Name);
                user.Password = password;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
            }
            else
                return PartialView("_EidtUser", user);
            return PartialView("_SettingsUsers", db.Users.ToList());
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            ViewBag.User = null;
            ViewBag.User = CreateUserDefault();
            return PartialView("_SettingsUsers", db.Users.ToList());

        }

        [HttpGet]
        public ActionResult SettingsPassword()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private User CreateUserDefault()
        {
            var user = new User();
            user.Name = "Login";
            user.Password = "Hasło";
            user.FirstName = "Imię";
            user.LastName = "Nazwisko";
            user.Email = "E-mail";
            return user;
        }
    }
}

EasyERP/EasyERP/Views/Shared/_Calendar.cshtml
<div id="kalendarz">
    <h2>Kalendarz</h2>
    <div id="data">
        
    </div>
</div>


EasyERP/EasyERP/Views/Shared/_ClientAddEdit.cshtml
@model EasyERP.Models.Client

@Scripts.Render("~/bundles/jquery")
@if (Model != null)
{
    @Html.ActionLink("Anuluj", "DetailsClient", "Clients", new { id = Model.ClientId }, htmlAttributes: new { @class = "button" })
}
else
{
    @Html.ActionLink("Anuluj", "AllClients", "", htmlAttributes: new { @class = "button" })
}
<input type="submit" value="Zapisz" class="button zapisz transition">
<table>
    <tr>
        <td>Nazwa firmy</td>
        <td>@Html.EditorFor(m => m.Company)</td>
        <td>Kod firmy</td>
        <td>@Html.DisplayFor(m => m.CompanyCode)</td>
    </tr>
    <tr>
        <td>Imię</td>
        <td>
            @Html.EditorFor(m => m.FirstName)
        </td>
        <td>Nazwisko</td>
        <td>
            @Html.EditorFor(m => m.LastName)
        </td>
    </tr>
    <tr>
        <td>Telefon</td>
        <td>@Html.EditorFor(m => m.Phone)</td>
        <td>E-mail</td>
        <td>@Html.EditorFor(m => m.EmailAddress)</td>
    </tr>
    <tr>
        <td>REGON</td>
        <td>@Html.EditorFor(m => m.Regon)</td>
        <td>NIP</td>
        <td>@Html.EditorFor(m => m.Nip)</td>
    </tr>
    <tr>
        <td>Adres</td>
        <td>@Html.EditorFor(m => m.Address)</td>
        <td>Strona internetowa</td>
        <td>@Html.EditorFor(m => m.WebSiteAddress)</td>
    </tr>
    <tr>
        <td>Miasto</td>
        <td>@Html.EditorFor(m => m.City)</td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td>Kod pocztowy</td>
        <td>@Html.EditorFor(m => m.CountryCode)</td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td>Województwo</td>
        <td>@Html.EditorFor(m => m.Region)</td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td>Kraj</td>
        <td>@Html.EditorFor(m => m.Country)</td>
        <td colspan="2"></td>
    </tr>
</table>
@Html.ValidationSummary(false, "", new { @class = "text-danger alert" })

EasyERP/EasyERP/Views/Shared/_ClientDetails.cshtml
@model EasyERP.Models.Client

@Ajax.ActionLink("Edytuj dane", "EditClientAsync", "Clients", new { id = @Model.ClientId },
        new AjaxOptions
        {
            UpdateTargetId = "AddEdit",
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "Get"
        }, new { @class = "button" })
<table class="edit">
    <tr>
        <td>Nazwa firmy</td>
        <td>@Html.DisplayFor(m => m.Company)</td>
        <td>Kod firmy</td>
        <td>@Html.DisplayFor(m => m.CompanyCode)</td>
    </tr>
    <tr>
        <td>Imię</td>
        <td>
            @Html.DisplayFor(m => m.FirstName)
        </td>
        <td>Nazwisko</td>
        <td>
            @Html.DisplayFor(m => m.LastName)
        </td>
    </tr>
    <tr>
        <td>Telefon</td>
        <td>@Html.DisplayFor(m => m.Phone)</td>
        <td>E-mail</td>
        <td>@Html.DisplayFor(m => m.EmailAddress)</td>
    </tr>
    <tr>
        <td>REGON</td>
        <td>@Html.DisplayFor(m => m.Regon)</td>
        <td>NIP</td>
        <td>@Html.DisplayFor(m => m.Nip)</td>
    </tr>
    <tr>
        <td>Adres</td>
        <td>@Html.DisplayFor(m => m.Address)</td>
        <td>Strona internetowa</td>
        <td>@Html.DisplayFor(m => m.WebSiteAddress)</td>
    </tr>
    <tr>
        <td>Miasto</td>
        <td>@Html.DisplayFor(m => m.City)</td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td>Kod pocztowy</td>
        <td>@Html.DisplayFor(m => m.CountryCode)</td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td>Województwo</td>
        <td>@Html.DisplayFor(m => m.Region)</td>
        <td colspan="2"></td>
    </tr>
    <tr>
        <td>Kraj</td>
        <td>@Html.DisplayFor(m => m.Country)</td>
        <td colspan="2"></td>
    </tr>
</table>

EasyERP/EasyERP/Views/Shared/_ClientHead.cshtml

        <tr>
            <td>Numer klienta</td>
            <td>Nazwa firmy</td>
            <td>Imię</td>
            <td>Nazwisko</td>
            <td>Adres</td>
            <td>Miasto</td>
            <td>Województwo</td>
            <td>Kod pocztowy</td>
            <td>Kraj</td>
            <td>Numer telefonu</td>
            <td>E-mail</td>
            <td>Oferta</td>
            <td>Zamówienia</td>
        </tr>


EasyERP/EasyERP/Views/Shared/_EditUser.cshtml
@model EasyERP.Models.User

@*<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>*@
@Scripts.Render("~/bundles/jquery")
<div id="dane-konta">
    @using (Ajax.BeginForm("Edit", "Settings", null, new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "settings", InsertionMode = InsertionMode.Replace, OnSuccess = "onSuccess" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.UserId)

        @Ajax.ActionLink("Anuluj", "SettingsUsers", new {}, new AjaxOptions { UpdateTargetId = "settings", InsertionMode = InsertionMode.Replace, HttpMethod = "Get" }, htmlAttributes: new { @class = "button" })
        <input type="submit" value="Zapisz" class="button zapisz transition">
        <table class="edit">
            <tr>
                <td>
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })

                </td>
                <td>
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
        </table>
        <br />
        @Html.ValidationSummary(false, "", new { @class = "text-danger alert" })
    }
</div>

EasyERP/EasyERP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>EasyERP - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700,800&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Arimo:400,400italic&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <![endif]-->
</head>
<body class="zalogowany">
    <nav id="menu">
        <ul>
            <li><button class="transition" id="rozwin"></button></li>
            <li><a href="#">@Html.ActionLink("Dashboard", "Index", "Dashboard")</a></li>
            <li><a href="#">@Html.ActionLink("Klienci", "AllClients", "Clients")</a></li>
            <li><a href="#">@Html.ActionLink("Zamówienia", "Orders", "Orders")</a></li>
            <li><a href="#">@Html.ActionLink("Magazyn", "Index", "Products")</a></li>
            <li><a href="#">@Html.ActionLink("Dokumenty", "Index", "Dashboard")</a></li>
            <li><a href="#">@Html.ActionLink("Analiza", "Index", "Reports")</a></li>
        </ul>
    </nav>
    <section id="content">
        <div id="top">
            <div class="wrapper">
                <form method="post" class="alignleft align">
                    <input type="submit" name="szukaj" value=" " class="transition">
                    <input type="text" id="searcher" name="fraza" value="Wyszukaj klienta, zadanie, albo dokument..." onfocus="if (this.value == 'Wyszukaj klienta, zadanie, albo dokument...') {this.value = '';}" onblur="if (this.value == '')  {this.value = 'Wyszukaj klienta, zadanie, albo dokument...';}">
                </form>
                <div class="alignright align">
                    Administrator
                </div>
                <ul class="alignright align">
                    <li>
                        @if (Context.Session["FirstName"] != null && Context.Session["LastName"] != null)
                        {
                            <a href="#">@Context.Session["FirstName"].ToString() @Context.Session["LastName"].ToString()</a>
                        }
                        else
                        {
                            <a href="#">Andrzej Krawczyk</a>
                        }
                        <ul>
                            <li><a href="#">@Html.ActionLink("Ustawienia", "Basic", "Settings")</a></li>
                            <li><a href="#">@Html.ActionLink("Wyloguj", "Logout", "Account")</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div id="breadcrumbs">
            Jesteś na: <a href="#">@ViewBag.Title</a>
        </div>
        <div class="wrapper">
            @if (!String.IsNullOrEmpty(ViewBag.Error))
            {
                <table width="100%">
                    <tr>
                        <td align="center">
                            <div class="alert align error max-top">Błąd: @ViewBag.Error</div>
                        </td>
                    </tr>
                </table>
            }
            @if (!String.IsNullOrEmpty(ViewBag.Success))
            {
                <table width="100%" id="success">
                    <tr>
                        <td align="center">
                            <div class="alert alignleft align info max-top">@ViewBag.Success</div>
                        </td>
                    </tr>
                </table>
            }
            @RenderBody()
        </div>
    </section>
    @Html.Hidden("controllerName", ViewContext.RouteData.Values["Controller"].ToString())
</body>
</html>

EasyERP/EasyERP/Views/Shared/_Products.cshtml
@model List<EasyERP.Models.HelpModels.Basket>

<table class="edit">
    <thead>
        <tr>
            <th>Produkty</th>
            <th>Ilość</th>
            <th>Cena</th>
            <th>Akcja</th>
        </tr>
    </thead>
    <tbody>
        @foreach (EasyERP.Models.HelpModels.Basket product in Model)
        {
            <tr>
                <td>@product.Product.Name</td>
                <td>@product.Amount</td>
                <td>@product.Product.PurchasePrice</td>
                <td class="akcja"><a href="#" class="true"></a><a href="#" class="false"></a><a href="#" class="delete"></a></td>
            </tr>
        }
        <tr class="empty">
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
        </tr>
    </tbody>
</table>

EasyERP/EasyERP/Views/Shared/_SettingsTemplateCreate.cshtml
@model EasyERP.Models.Template

@Scripts.Render("~/bundles/Common")
@*@using (Ajax.BeginForm("Create", null, new AjaxOptions() { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "settings" }, new { enctype = "multipart/form-data", id = "produkty", @class = "dropzone" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(false, "", new { @class = "text-danger alert" })

    <h1 class="bold">Dodaj szablon</h1>
    @Html.ActionLink("Anuluj", "Index", "Products", "", htmlAttributes: new { @class = "button" })
    <input type="submit" value="Zapisz" class="button zapisz transition" />

    <table class="edit">
        <thead>
            <tr>
                <td>
                    @Html.LabelFor(model => model.TemplateName, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.TemplateName, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    <input type="file" name="file" id="file" />
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Html.LabelFor(model => model.EnteredOn, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.EnteredOn, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                </td>
                <td>
                    @Html.EditorFor(model => model.IsActive)
                </td>
            </tr>
        </tbody>
    </table>
}*@




